config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'user#home'
  get 'user/login'
  get 'user/logout'
  
  resources :user do
    member { get :shopping_list }
  end
  
  resources :products, only: [:create]
  get '/admin/products', to: 'products#index'

  resources :shopping_list, only:[:new,:create,:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :shopping_lists
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
        authenticated = UserAuthenticated.last
        if authenticated.id_user_authenticated.nil?
            redirect_to "/", notice: "Usuário sem permissão."
        else
            user = User.find(authenticated.id_user_authenticated)
            if !user.admin
                redirect_to "/", notice: "Usuário sem permissão."
            else
                @users = User.all
                @id_admin = user.id
            end
        end
    end

    def new
        @user = User.new
    end

    def create 
        user_fisrt_name = params[:first_name]
        user_last_name = params[:last_name]
        user_age = params[:age]
        user_password = params[:password]
        user_admin = params[:admin]
        user_name = User.find_by(first_name: user_fisrt_name)

        if !user_name.nil?
            redirect_to "/user/new", notice: "Usuário já cadastrado."
        elsif user_fisrt_name == ""
            redirect_to "/user/new", notice: "Preencha o campo 'Primeiro Nome:'."
        elsif user_last_name == ""
            redirect_to "/user/new", notice: "Preencha o campo 'Segundo Nome:'."
        elsif user_age == ""
            redirect_to "/user/new", notice: "Preencha o campo 'Idade:'."
        elsif user_password == ""
            redirect_to "/user/new", notice: "Digite uma senha."
        else
            user = User.create(first_name: user_fisrt_name,last_name: user_last_name,age: user_age,password: user_password,admin: user_admin)
            redirect_to "/", notice: "Cadastro realizado com sucesso."
        end
    end

    def show
        id_user = params[:id]
        id_authenticated = id_user.to_i
        authenticated = UserAuthenticated.last
        if authenticated.id_user_authenticated != id_authenticated
            redirect_to "/", notice: "Usuário sem permissão."
        else
            @user = User.find_by(id: id_user)
        end   
    end

    def edit
        @user = User.find(params[:id])
        authenticated = UserAuthenticated.last
        if @user.id != authenticated.id_user_authenticated
            redirect_to "/", notice: "Usuário sem permissão."
        end        
    end

    def update
        user_params = params.require(:user).permit(:first_name, :last_name, :age, :password)
        user_id = params[:id]
        user_name = User.find_by(first_name: user_params[:first_name])

        if !user_name.nil? and user_name.id.to_i != user_id.to_i

            redirect_to "/user/#{user_id}/edit", notice: "Usuário já cadastrado."
        elsif user_params[:first_name] == ""
            redirect_to "/user/#{user_id}/edit", notice: "Preencha o campo 'Primeiro Nome:'."
        elsif user_params[:last_name] == ""
            redirect_to "/user/#{user_id}/edit", notice: "Preencha o campo 'Segundo Nome:'."
        elsif user_params[:age] == ""
            redirect_to "/user/#{user_id}/edit", notice: "Preencha o campo 'Idade:'."
        elsif user_params[:password] == ""
            redirect_to "/user/#{user_id}/edit", notice: "Digite uma senha."
        else
            user = User.find_by(id: user_id)
            user.first_name = user_params[:first_name]
            user.last_name = user_params[:last_name]
            user.age = user_params[:age]
            user.password = user_params[:password]
            user.save
            redirect_to "/user/#{user.id}", notice: "Atualização do usuário executada com suscesso."
        end
    end

    def destroy
        authenticated = UserAuthenticated.last
        id_admin = authenticated.id_user_authenticated
        
        user_id = params[:id]
        user = User.find(user_id)
        lists = user.shopping_lists
        lists.each do |row|
            ShoppingList.destroy_by(id: row.id)
            ListProduct.destroy_by(shopping_list_id: row.id)
        end

        User.destroy_by(id: user_id)
        redirect_to "/user/#{id_admin}", notice: "Usuário excluido com sucesso."
    end

    def shopping_list
        @user = User.find(params[:id])
        authenticated = UserAuthenticated.last
        if @user.id != authenticated.id_user_authenticated
            redirect_to "/", notice: "Usuário sem permissão."
        else
            if @user.nil?
                redirect_to "/", notice: "Usuário não cadastrado."
            else
                @n_list = @user.shopping_lists
                
                if @n_list.nil?
                    redirect_to "/user/#{@user.id}", notice: "Usuário não possui lista cadastrada."
                else
                    @shopping_list = @n_list.map { |row| row.products }
                end
        end
    end 
    end

    def home
    end

    def login
        first_name = params[:first_name]
        password = params[:password]
        user = User.find_by(first_name: first_name)
        if user.nil?
            redirect_to "/", notice: "Usuário não cadastrado."
        elsif user.password != password
            redirect_to "/", notice: "Senha incorreta."
        else
            user_authenticated = UserAuthenticated.create(id_user_authenticated: user.id)
            redirect_to "/user/#{user.id}" 
        end
    end

    def logout
        user = UserAuthenticated.last
        user.id_user_authenticated = ""
        user.save 
        redirect_to "/", notice: "Logout efetuado com suscesso."
    end
    
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<p style="color: red"><%= notice %></p>

<div>
    <h1>Atualizar Cadastro</h1>
    <%= form_with(model: @user)  do |form| %>
        <div>
            <%= form.label :first_name, "Primeiro nome:" %>
            <br>
            <%= form.text_field :first_name %>
        </div>
        <div>
            <%= form.label :last_name, "Segundo nome:" %>
            <br>
            <%= form.text_field :last_name %>
        </div>
        <div>
            <%= form.label :age, "Idade:" %>
            <br>
            <%= form.text_field :age %>
        </div>
        <div>
            <%= form.label :password, "Senha:" %>
            <br>
            <%= form.text_field :password %>
        </div>
        <br>
        <div>
            <%= form.submit "Atualizar"%>
        </div>
    <% end %>
</div>
<p>-------------------------------------------------------</p>
<%= button_to "Voltar", user_path(@user.id), method: :get %>

app/views/user/home.html.erb
<p style="color: green"><%= notice %></p>
<div>
    <h1>Login</h1>
    <%= form_with url: user_login_path, method: :get  do |form| %>
        <div>
            <%= form.label :first_name, "Primeiro nome:" %>
            <br>
            <%= form.text_field :first_name %>
        </div>

        <div>
            <%= form.label :password, "Senha:" %>
            <br>
            <%= form.password_field :password %>
        </div>
        <br>
        <div>
            <%= form.submit "Entrar"%>
        </div>
    <% end %>
    <p>-------------------------------------------------------</p>
    <div>
        <%= button_to "Cadastrar", new_user_path, method: :get  %>    
    </div>    
</div>

app/views/user/index.html.erb
<p style="color: green"><%= notice %></p>
<h1> Usuários </h1>
<style>
    table{
        border: 1px solid #ccc;
    }
    table tr th {
        border: 1px solid #ccc;
        font-weight: bold;
    }
    table tr td {
        border: 1px solid #ccc;
    }
</style>
    <table>
        <tr>
            <th>ID</th>
            <th>Primeiro Nome</th>
            <th>Segundo Nome</th>
            <th>Idade</th>
            <th>Senha</th>
            <th>Admin</th>
            <th></th>
        </tr>
        <% @users.each do |user|%>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.age %></td>
            <td><%= user.password %></td>
            <td><%= user.admin %></td>
            <% if user.admin == true %>
                <td></td>
            <% else %>
                <td><%= button_to "Excluir", user_path(user.id), method: :delete %> </td>
            <% end %>
        </tr>
        <% end %>
    </table>
    <br>
</div><%= button_to "Voltar", user_path(@id_admin), method: :get  %>

app/views/user/new.html.erb
<p style="color: red"><%= notice %></p>

<div>
    <h1>Cadastro</h1>
    <%= form_with url: user_index_path, method: :post  do |form| %>
        <div>
            <%= form.label :first_name, "Primeiro nome:" %>
            <br>
            <%= form.text_field :first_name %>
        </div>
        <div>
            <%= form.label :last_name, "Segundo nome:" %>
            <br>
            <%= form.text_field :last_name %>
        </div>
        <div>
            <%= form.label :age, "Idade:" %>
            <br>
            <%= form.text_field :age %>
        </div>
        <div>
            <%= form.label :password, "Senha:" %>
            <br>
            <%= form.password_field :password %>
        </div>
        <br>
        <div>
            <%= form.check_box :admin %>
            <%= form.label :admin, "Admin" %>         
        </div>
        <br>
        <div>
            <%= form.submit "Cadastrar"%>
        </div>
    <% end %>
</div>
<p>-------------------------------------------------------</p>
<%= button_to "Voltar", root_path, method: :get %>

app/views/user/shopping_list.html.erb
<p style="color: green"><%= notice %></p>
<%= button_to "Voltar", user_path(@user.id), method: :get %>
<style>
    table{
        border: 1px solid #ccc;
    }
    table tr th {
        border: 1px solid #ccc;
        font-weight: bold;
    }
    table tr td {
        border: 1px solid #ccc;
    }
</style>
<% j=0 %>
<p>----------------------------------------</p>
<% for i in 1..@shopping_list.length%>
    <h1> Lista <%= @n_list[j].id %> </h1>
    <table>
        <tr>
            <th>Lista</th>
            <th>Produto</th>
            <th>Valor</th>
        </tr>
        <% @shopping_list[j].each do |row|%>
        <tr>
            <td><%= row.id %></td>
            <td><%= row.name %></td>
            <td><%= row.value %></td>
        </tr>
        <% end %>
    </table>
    <br>   
    <%= button_to "Excluir", shopping_list_path(@n_list[j].id), method: :delete %>  
    <br>
    <% j=j+1 %>
    <p>----------------------------------------</p>
<% end %>
<%= button_to "Cadastra nova lista", new_shopping_list_path, method: :get %>

app/views/user/show.html.erb
<p style="color: green"><%= notice %></p>
<h1> <%= @user.first_name %> <%= @user.last_name %> </h1>
<p>Idade: <%= @user.age %></p>
<p>Senha: <%= @user.password %></p>
<% if @user.admin? %>
    <p>-----------------Usuário Administrador-------------------</p>
    <%= button_to "Cadastro de produtos", admin_products_path, method: :get %>
    <br>
    <%= button_to "Usuários", user_index_path, method: :get %>
    <p>---------------------------------------------------------</p>
<% end %>

<div>
  <%= link_to "Alterar", edit_user_path(@user.id) %> |
  <%= link_to "Lista de Compras", shopping_list_user_path(@user.id) %> |
  <%= link_to "Sair", user_logout_path %>  
</div>