config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'user#home'
  get 'user/login'
  get 'user/logout'
  
  resources :user do
    member { get :shopping_list }
  end
  
  resources :products, only: [:create]
  get '/admin/products', to: 'products#index'

  resources :shopping_list, only:[:new,:create,:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :list_products
    has_many :shopping_lists, through: :list_products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :verify_authenticity_token
 
    def index
        authenticated = UserAuthenticated.last
        if authenticated.id_user_authenticated.nil?
            redirect_to "/", notice: "Usuário sem permissão."
        else
            user = User.find(authenticated.id_user_authenticated)
            if !user.admin
                redirect_to "/", notice: "Usuário sem permissão."
            else
                @products = Product.all
                @id_admin = user.id
            end
        end
    end

    def create
        id_admin = params[:id_admin]
        product_name = params[:name]
        product_value = params[:value]

        Product.create(name: product_name,value: product_value)
        redirect_to "/user/#{id_admin}", notice: "Cadastro realizado com sucesso."
    end
    
end

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>
<style>
    table{
        border: 1px solid #ccc;
    }
    table tr th {
        border: 1px solid #ccc;
        font-weight: bold;
    }
    table tr td {
        border: 1px solid #ccc;
    }

</style>
<h1>Produtos Cadastrados</h1>
<table>
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Valor</th>
    </tr>
    <% @products.each do |row|%>
        <tr>
          <td><%= row.id %></td>
          <td><%= row.name %></td>
          <td><%= row.value %></td>
        </tr>
      <% end %>
</table>
<p>-------------------------------------------------------</p>
<div>
    <h1>Cadastrar produto</h1>
    <%= form_with url: products_path, method: :post do |form| %>
        <div>
            <%= form.hidden_field :id_admin, value: "#{@id_admin}" %>
            <%= form.label :name, "Nome do Produto:" %>
            <br>
            <%= form.text_field :name %>
        </div>
        <div>
            <%= form.label :value, "Valor:" %>
            <br>
            <%= form.text_field :value %>
        </div>
        <br>
        <div>
            <%= form.submit "Cadastrar"%>
        </div>
    <% end %>
</div>
<p>-------------------------------------------------------</p>
</div><%= button_to "Voltar", user_path(@id_admin), method: :get  %>